### ISSUE TITLE
DB data not in sync with local file data

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-contentplugin#8]
Plugin Management UI shows an older version, but update version is disabled. An export contains a later version of plugin files, which suggests the DB data is out-of-date.

**Comment by chris-steele** [comment]
I don't see any issues in a clean install. @taylortom do you have any steps to replicate?

**Comment by taylortom** [comment]
This was originally reported by Dan. May be an issue with the specific install (versions/infra). Will put back in the backlog for now.

**Comment by taylortom** [comment]
@chris-steele I'm getting an error for any locally installed plugins (i.e. those from a zip/import, not installed via the CLI).

Can you look into supressing this in these cases?

**Comment by chris-steele** [comment]
@taylortom I tried an import with adapt-pageNav, but did not see the above error. What have you got in your database for the adapt-pageNav/adapt-hotgrid entries?

**Comment by taylortom** [comment]
Below is the DB data, the local package.json files look to match these versions.

```json
{
    "_id" : "669006b7c96a1b0f4247219c",
    "name" : "adapt-pageNav",
    "version" : "3.1.6",
    "framework" : ">=5.30.2",
    "displayName" : "Page Navigation",
    "targetAttribute" : "_pageNav",
    "description" : "Navigation bar that is displayed within Adapt content pages, typically at the bottom.",
    "type" : "component",
    "isLocalInstall" : true,
    "isEnabled" : true,
    "isAddedByDefault" : false
},
{
    "_id" : "669006c1c96a1b0f424721a8",
    "name" : "adapt-hotgrid",
    "version" : "4.6.0",
    "framework" : ">=5.33.10",
    "targetAttribute" : "_hotgrid",
    "displayName" : "Hotgrid",
    "description" : "A component that displays selectable images in a grid format.",
    "type" : "component",
    "isLocalInstall" : true,
    "isEnabled" : true,
    "isAddedByDefault" : false
}

```

***

As a sidenote, I think we could do with logging the actual version mismatch (i.e. the expected + actual) to help with debugging.

**Comment by chris-steele** [comment]
@taylortom with the [PR ](https://github.com/adapt-security/adapt-authoring-contentplugin/pull/13) does it shed any more light on the issue you are having?
